export const labReports = [
  { id: "rep1", testName: "Complete Blood Count", date: "2024-07-15", doctor: "Dr. Rajesh Kumar", status: "Completed" },
  { id: "rep2", testName: "Liver Function Test", date: "2024-07-16", doctor: "Dr. Priya Sharma", status: "Completed" },
  { id: "rep3", testName: "Lipid Profile", date: "2024-06-20", doctor: "Dr. Rajesh Kumar", status: "Completed" },
  { id: "rep4", testName: "Thyroid Function Test", date: "2024-07-16", doctor: "Dr. Priya Sharma", status: "Processing" },
  { id: "rep5", testName: "Urinalysis", date: "2024-07-17", doctor: "Dr. Rajesh Kumar", status: "Pending" },
  { id: "rep6", testName: "HbA1c", date: "2024-06-20", doctor: "Dr. Rajesh Kumar", status: "Completed" },
  { id: "rep13", testName: "Vitamin D Level", date: "2024-06-20", doctor: "Dr. Rajesh Kumar", status: "Completed" },
  { id: "rep7", testName: "Complete Blood Count", date: "2024-04-10", doctor: "Dr. Rajesh Kumar", status: "Completed" },
  { id: "rep8", testName: "Liver Function Test", date: "2024-01-05", doctor: "Dr. Priya Sharma", status: "Completed" },
  { id: "rep9", testName: "Chest X-Ray", date: "2024-07-10", doctor: "Dr. Rajesh Kumar", status: "Completed", type: "x-ray" },
  { id: "rep10", testName: "MRI Brain Scan", date: "2024-05-12", doctor: "Dr. Arjun Kumar", status: "Completed", type: "mri" },
  { id: "rep11", testName: "Abdominal Ultrasound", date: "2024-07-18", doctor: "Dr. Priya Sharma", status: "Processing", type: "x-ray" },
  { id: "rep12", testName: "CT Scan Abdomen", date: "2024-02-25", doctor: "Dr. Arjun Kumar", status: "Completed", type: "mri" },
  { id: "rep14", testName: "Serum Creatinine", date: "2024-07-18", doctor: "Dr. Priya Sharma", status: "Completed" },
  { id: "rep15", testName: "Urine Culture", date: "2024-07-18", doctor: "Dr. Priya Sharma", status: "Completed" },
  { id: "rep16", testName: "Vitamin B12 Level", date: "2024-06-20", doctor: "Dr. Rajesh Kumar", status: "Completed" },
  { id: "rep17", testName: "ESR (Erythrocyte Sedimentation Rate)", date: "2024-07-15", doctor: "Dr. Rajesh Kumar", status: "Completed" },
  { id: "rep18", testName: "ECG", date: "2024-07-10", doctor: "Dr. Rajesh Kumar", status: "Completed", type: "Cardiology" },
];
